print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill? $"))
split_total = "{:.2f}".format(round(total_bill * (1 + tip/100) / people))
print(f"Each person should pay: ${split_total}")